baseURL = "http://uekoetter.dev/"
languageCode = "de-de"
title = "Jonas"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true

[params]
  author = "Jonas Uekötter"
  description = ""
  title = "Jonas Uekötter"
  favicon = "https://uekoetter.dev/favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "© 2021"

# socials can be found in header.html
[menu]  
  [[menu.main]]
    name = "📝 Blog"
    url = "/blog"
    weight = 1

  [[menu.main]]
    name = "❤️ Donate"
    url = "/donate"
    weight = 1

  [[menu.main]]
    name = "📦 OSS"
    url = "/dashboard"
    weight = 1


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true